spring.application.name=user-service
server.port=8081

eureka.client.service-url.defaultZone=http://${EUREKA_HOST:localhost}:8761/eureka/
eureka.instance.prefer-ip-address=true

# Database configuration (MySQL setup)
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/user_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:cdac}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=9a2f34827d32c918ef938472918bc321de38a928374e2d312bc83c928b3e2a12
jwt.expiration=86400000

# Spring Mail Configuration (Uncomment and configure to send real emails)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=driveptwop@gmail.com
spring.mail.password=mpiaudfqhvtdizzh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

